-- MySQL Script generated by MySQL Workbench
-- Tue 20 Feb 2024 11:18:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema LittleLemonDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `LittleLemonDB` ;

-- -----------------------------------------------------
-- Schema LittleLemonDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LittleLemonDB` ;
USE `LittleLemonDB` ;

-- -----------------------------------------------------
-- Table `LittleLemonDB`.`MENU`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LittleLemonDB`.`MENU` ;

CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`MENU` (
  `MENU_ID` INT NOT NULL AUTO_INCREMENT,
  `MENU_NAME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`MENU_ID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `MENU_ID_UNIQUE` ON `LittleLemonDB`.`MENU` (`MENU_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`CUSTOMER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LittleLemonDB`.`CUSTOMER` ;

CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`CUSTOMER` (
  `CUS_ID` INT NOT NULL AUTO_INCREMENT,
  `CUS_FNAME` VARCHAR(45) NOT NULL,
  `CUS_LNAME` VARCHAR(45) NOT NULL,
  `MENU_ID` INT NOT NULL,
  PRIMARY KEY (`CUS_ID`),
  CONSTRAINT `MENU_ID`
    FOREIGN KEY ()
    REFERENCES `LittleLemonDB`.`MENU` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `CUS_ID_UNIQUE` ON `LittleLemonDB`.`CUSTOMER` (`CUS_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`CONTACT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LittleLemonDB`.`CONTACT` ;

CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`CONTACT` (
  `CONT_ID` INT NOT NULL AUTO_INCREMENT,
  `CONT_NUMBER` VARCHAR(45) NOT NULL,
  `CUS_ID` INT NOT NULL,
  PRIMARY KEY (`CONT_ID`),
  CONSTRAINT `CUS_ID`
    FOREIGN KEY (`CUS_ID`)
    REFERENCES `LittleLemonDB`.`CUSTOMER` (`CUS_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `CONT_ID_UNIQUE` ON `LittleLemonDB`.`CONTACT` (`CONT_ID` ASC) VISIBLE;

CREATE UNIQUE INDEX `CONT_NUMBER_UNIQUE` ON `LittleLemonDB`.`CONTACT` (`CONT_NUMBER` ASC) VISIBLE;

CREATE INDEX `CUS_ID_idx` ON `LittleLemonDB`.`CONTACT` (`CUS_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`ADDRESS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LittleLemonDB`.`ADDRESS` ;

CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`ADDRESS` (
  `ADDR_ID` INT NOT NULL AUTO_INCREMENT,
  `ADDR_STREET` VARCHAR(45) NOT NULL,
  `ADDR_CITY` VARCHAR(45) NOT NULL,
  `ADDR_POSTCODE` INT NOT NULL,
  `ADDR_COUNTRY` VARCHAR(45) NOT NULL,
  `CUS_ID` INT NOT NULL,
  PRIMARY KEY (`ADDR_ID`),
  CONSTRAINT `CUS_ID`
    FOREIGN KEY (`CUS_ID`)
    REFERENCES `LittleLemonDB`.`CUSTOMER` (`CUS_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ADDR_ID_UNIQUE` ON `LittleLemonDB`.`ADDRESS` (`ADDR_ID` ASC) VISIBLE;

CREATE INDEX `CUS_ID_idx` ON `LittleLemonDB`.`ADDRESS` (`CUS_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`BOOKING`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LittleLemonDB`.`BOOKING` ;

CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`BOOKING` (
  `BOOK_ID` INT NOT NULL AUTO_INCREMENT,
  `BOOK_DATE` DATETIME NOT NULL,
  `BOOK_TABLE_NUMBER` INT NOT NULL,
  `CUS_ID` INT NOT NULL,
  PRIMARY KEY (`BOOK_ID`),
  CONSTRAINT `CUS_ID`
    FOREIGN KEY (`CUS_ID`)
    REFERENCES `LittleLemonDB`.`CUSTOMER` (`CUS_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `BOOK_ID_UNIQUE` ON `LittleLemonDB`.`BOOKING` (`BOOK_ID` ASC) VISIBLE;

CREATE INDEX `CUS_ID_idx` ON `LittleLemonDB`.`BOOKING` (`CUS_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`ORDER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LittleLemonDB`.`ORDER` ;

CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`ORDER` (
  `ORD_ID` INT NOT NULL AUTO_INCREMENT,
  `ORD_DATE` DATETIME NOT NULL,
  `ORD_QUANTITY` INT NOT NULL,
  `ORD_TOTALCOST` DECIMAL(9,2) NOT NULL,
  `CUS_ID` INT NOT NULL,
  `MENU_ID` INT NOT NULL,
  PRIMARY KEY (`ORD_ID`),
  CONSTRAINT `CUS_ID`
    FOREIGN KEY (`CUS_ID`)
    REFERENCES `LittleLemonDB`.`CUSTOMER` (`CUS_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MENU_ID`
    FOREIGN KEY (`MENU_ID`)
    REFERENCES `LittleLemonDB`.`MENU` (`MENU_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ORD_ID_UNIQUE` ON `LittleLemonDB`.`ORDER` (`ORD_ID` ASC) VISIBLE;

CREATE INDEX `CUS_ID_idx` ON `LittleLemonDB`.`ORDER` (`CUS_ID` ASC) VISIBLE;

CREATE INDEX `MENU_ID_idx` ON `LittleLemonDB`.`ORDER` (`MENU_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`ORDERSTATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LittleLemonDB`.`ORDERSTATUS` ;

CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`ORDERSTATUS` (
  `ORDSTAT_ID` INT NOT NULL AUTO_INCREMENT,
  `ORDSTAT_DATE` DATETIME NOT NULL,
  `ORD_ID` INT NOT NULL,
  PRIMARY KEY (`ORDSTAT_ID`),
  CONSTRAINT `ORD_ID`
    FOREIGN KEY (`ORD_ID`)
    REFERENCES `LittleLemonDB`.`ORDER` (`ORD_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ORDSTAT_ID_UNIQUE` ON `LittleLemonDB`.`ORDERSTATUS` (`ORDSTAT_ID` ASC) VISIBLE;

CREATE INDEX `ORD_ID_idx` ON `LittleLemonDB`.`ORDERSTATUS` (`ORD_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`COURSE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LittleLemonDB`.`COURSE` ;

CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`COURSE` (
  `COUR_ID` INT NOT NULL AUTO_INCREMENT,
  `COUR_NAME` VARCHAR(45) NOT NULL,
  `MENU_ID` INT NOT NULL,
  PRIMARY KEY (`COUR_ID`),
  CONSTRAINT `MENU_ID`
    FOREIGN KEY (`MENU_ID`)
    REFERENCES `LittleLemonDB`.`MENU` (`MENU_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `COUR_ID_UNIQUE` ON `LittleLemonDB`.`COURSE` (`COUR_ID` ASC) VISIBLE;

CREATE INDEX `MENU_ID_idx` ON `LittleLemonDB`.`COURSE` (`MENU_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`DRINK`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LittleLemonDB`.`DRINK` ;

CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`DRINK` (
  `DRK_ID` INT NOT NULL AUTO_INCREMENT,
  `DRK_NAME` VARCHAR(45) NOT NULL,
  `MENU_ID` INT NOT NULL,
  PRIMARY KEY (`DRK_ID`),
  CONSTRAINT `MENU_ID`
    FOREIGN KEY (`MENU_ID`)
    REFERENCES `LittleLemonDB`.`MENU` (`MENU_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `DRK_ID_UNIQUE` ON `LittleLemonDB`.`DRINK` (`DRK_ID` ASC) VISIBLE;

CREATE INDEX `MENU_ID_idx` ON `LittleLemonDB`.`DRINK` (`MENU_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`DESSERT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LittleLemonDB`.`DESSERT` ;

CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`DESSERT` (
  `DESS_ID` INT NOT NULL AUTO_INCREMENT,
  `DESS_NAME` VARCHAR(45) NOT NULL,
  `MENU_ID` INT NOT NULL,
  PRIMARY KEY (`DESS_ID`),
  CONSTRAINT `MENU_ID`
    FOREIGN KEY (`MENU_ID`)
    REFERENCES `LittleLemonDB`.`MENU` (`MENU_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `DESS_ID_UNIQUE` ON `LittleLemonDB`.`DESSERT` (`DESS_ID` ASC) VISIBLE;

CREATE INDEX `MENU_ID_idx` ON `LittleLemonDB`.`DESSERT` (`MENU_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`STAFF`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LittleLemonDB`.`STAFF` ;

CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`STAFF` (
  `STF_ID` INT NOT NULL AUTO_INCREMENT,
  `STF_NAME` VARCHAR(45) NOT NULL,
  `STF_SALARY` DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (`STF_ID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `STF_ID_UNIQUE` ON `LittleLemonDB`.`STAFF` (`STF_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `LittleLemonDB`.`ROLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `LittleLemonDB`.`ROLE` ;

CREATE TABLE IF NOT EXISTS `LittleLemonDB`.`ROLE` (
  `ROL_ID` INT NOT NULL AUTO_INCREMENT,
  `ROL_TYPE` VARCHAR(45) NOT NULL,
  `STF_ID` INT NOT NULL,
  PRIMARY KEY (`ROL_ID`),
  CONSTRAINT `STF_ID`
    FOREIGN KEY (`STF_ID`)
    REFERENCES `LittleLemonDB`.`STAFF` (`STF_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `ROL_ID_UNIQUE` ON `LittleLemonDB`.`ROLE` (`ROL_ID` ASC) VISIBLE;

CREATE INDEX `STF_ID_idx` ON `LittleLemonDB`.`ROLE` (`STF_ID` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
